version: '2'

services:
    brain:
        image: davoclavo/openag_brain
        # build: https://github.com/davoclavo/openag_brain.git#develop
        container_name: brain
        expose:
            - 5000
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
            - "/dev/video0:/dev/video0"
            # https://github.com/openaginitiative/openag_brain/blob/develop/nodes/arduino_handler.py#L322
            - "/dev/ttyACM0:/dev/serial/by-id/arduino"
        command: /home/pi/catkin_ws/devel/env.sh rosrun openag_brain main personal_food_computer_v2.launch -D http://db:5984 -A http://brain:5000  --screen
        depends_on:
            - db
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
    db:
        image: dogi/rpi-couchdb
        container_name: db
        expose:
            - 5984
        ports:
            - 5984:5984
            - 80:5984
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
